import { Project } from './models/project';

export const emptyProjects: Project[] = [
  {
    title1: ' ',
    title2: [' '],
    iconSpine: '#',
    descriptions: [' '],
    type: [' '],
    iconsTechnologies: ['#'],
    url: '#',
  },
  {
    title1: ' ',
    title2: [' '],
    iconSpine: '#',
    descriptions: [' '],
    type: [' '],
    iconsTechnologies: ['#'],
    url: '#',
  }];
export const projects: Project[] = [
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
  {
    title1: 'Portfolio',
    title2: ['Portfolio', 'Web'],
    iconSpine: 'assets/images/icons-band/brackets.svg',
    descriptions: [
      'Responsive website about me.',
      'Exhibition of all my personal projects.',
      'Deploiment to GitHub Pages.',
    ],
    type: ['SPA'],
    iconsTechnologies: [
      'assets/images/icons-band/angular.png',
      'assets/images/icons-band/ts.png',
      'assets/images/icons-band/html.png',
      'assets/images/icons-band/css.png',
      'assets/images/icons-band/github.png',
    ],
    url: 'https://github.com/Diego-Castiblanque-Alberca/Portfolio',
  },
];
